export const locations = [
    {
        id: 0,
        locationName: "Rite Aid #5429",
        address: "500 S Broadway, Los Angeles, CA 90013",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.facebook.com/HistoricFarmersMarket/",
        geoPoint: { lat: 34.047868, long: -118.25066 },
    },
    {
        id: 1,
        locationName: "Bank Of America",
        address: "333 S Hope St, Los Angeles, CA 90071",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL:
            "https://www.facebook.com/pg/BankOfAmericaFM/posts/?ref=page_internal",
        geoPoint: { lat: 34.053372, long: -118.253667 },
    },
    {
        id: 2,
        locationName: "Flower Marke-572",
        address: "755 Wall St, Los Angeles, CA 90014",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.laflowerdistrict.com/farmers-market",
        geoPoint: { lat: 34.041197, long: -118.249925 },
    },
    {
        id: 3,
        locationName: "D J Star Nails",
        address: "1632 Sunset Blvd, Los Angeles, CA 90026",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://seela.org/markets-echo-park/",
        geoPoint: { lat: 34.077002, long: -118.258377 },
    },
    {
        id: 4,
        locationName: "Adams/Vermont Cert Farmers Market",
        address: "1432 W Adams Blvd, Los Angeles, CA 90007",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.facebook.com/adamsvermontfm/",
        geoPoint: { lat: 34.032965, long: -118.292844 },
    },
    {
        id: 5,
        locationName: "Central Avenue Farmers' Market",
        address: "4301 S Central Ave, Los Angeles, CA 90011",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://seela.org/markets-central-avenue/",
        geoPoint: { lat: 34.005519, long: -118.256774 },
    },
    {
        id: 6,
        locationName: "Yummy",
        address: "3607 Sunset Blvd, Los Angeles, CA 90026",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.instagram.com/silverlakefarmersmarket/?hl=en",
        geoPoint: { lat: 34.090354, long: -118.276937 },
    },
    {
        id: 7,
        locationName: "Yummy",
        address: "3607 Sunset Blvd, Los Angeles, CA 90026",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.instagram.com/silverlakefarmersmarket/?hl=en",
        geoPoint: { lat: 34.090354, long: -118.276937 },
    },
    {
        id: 8,
        locationName: "Larchmont Village Cfm",
        address: "209 N Larchmont Blvd, Los Angeles, CA 90004",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.facebook.com/LarchmontVillageFM",
        geoPoint: { lat: 34.074937, long: -118.323948 },
    },
    {
        id: 9,
        locationName: "Wells Fargo Bank",
        address: "3250 Glendale Blvd, Los Angeles, CA 90039",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://seela.org/markets-atwater-village/",
        geoPoint: { lat: 34.118141, long: -118.260108 },
    },
    {
        id: 10,
        locationName: "East Hollywood Farmer's Market",
        address: "5448 Hollywood Blvd, Los Angeles, CA 90027",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.ehfarmersmkt.com/",
        geoPoint: { lat: 34.101498, long: -118.308518 },
    },
    {
        id: 11,
        locationName: "East Hollywood Farmer's Market",
        address: "5448 Hollywood Blvd, Los Angeles, CA 90027",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.ehfarmersmkt.com/",
        geoPoint: { lat: 34.101498, long: -118.308518 },
    },
    {
        id: 12,
        locationName: "Wellington Square Farmers Market",
        address: "4394 W Washington Blvd, Los Angeles, CA 90016",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.wellingtonsquarefarmersmarket.com/",
        geoPoint: { lat: 34.039559, long: -118.3351 },
    },
    {
        id: 13,
        locationName: "East La Farmers Market",
        address: "4801 E 3rd St, East Los Angeles, CA 90022",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.facebook.com/Eastlafm/",
        geoPoint: { lat: 34.033876, long: -118.16068 },
    },
    {
        id: 14,
        locationName: "Hw3.5",
        address: "1600 Ivar Ave, Hollywood, CA 90028",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://seela.org/markets-hollywood/",
        geoPoint: { lat: 34.099538, long: -118.328172 },
    },
    {
        id: 15,
        locationName: "Huntington Park Farmers Market",
        address: "3401 E Florence Ave, Huntington Park, CA 90255",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.goodveg.org/",
        geoPoint: { lat: 33.972749, long: -118.205603 },
    },
    {
        id: 16,
        locationName: "Secure Mob",
        address: "913 Meridian Ave, South Pasadena, CA 91030",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://southpasadenafarmersmarket.org/",
        geoPoint: { lat: 34.115179, long: -118.157513 },
    },
    {
        id: 17,
        locationName: "City Of Alhambra Farmers Market",
        address: "100 S 2nd St, Alhambra, CA 91801",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL:
            "https://www.cityofalhambra.org/resources/certified-farmers-market",
        geoPoint: { lat: 34.093138, long: -118.12819 },
    },
    {
        id: 18,
        locationName: "Main Street Cafe",
        address: "3826 Main St, Culver City, CA 90232",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.culvercityfarmersmarket.org/",
        geoPoint: { lat: 34.025044, long: -118.394425 },
    },
    {
        id: 19,
        locationName: "Beverly Hills Farmers Market",
        address: "9300 Civic Center Dr, Beverly Hills, CA 90210",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://www.beverlyhills.org/exploring/farmersmarket/",
        geoPoint: { lat: 34.073657, long: -118.399101 },
    },
    {
        id: 20,
        locationName: "Howard Hughes Cfm",
        address: "6080 Center Dr, Los Angeles, CA 90045",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL:
            "https://www.facebook.com/pg/HowardHughesFarmersMarket/about/?ref=page_internal",
        geoPoint: { lat: 33.976805, long: -118.391572 },
    },
    {
        id: 21,
        locationName: "U.S. Bank",
        address: "1800 Avenue of the Stars, Los Angeles, CA 90067",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "https://www.facebook.com/CenturyCityFM",
        geoPoint: { lat: 34.061032, long: -118.417364 },
    },
    {
        id: 22,
        locationName: "Del Taco Holdings Llc",
        address: "8651 La Tijera Blvd, Los Angeles, CA 90045",
        hasEBT: true,
        hasMarketMatch: true,
        rewards: null,
        coupons: null,
        contact: "NO CONTACT",
        websiteURL: "http://westchesterfarmersmkt.com/",
        geoPoint: { lat: 33.95868, long: -118.393206 },
    },
]

export default locations
