import { Location } from "./types/mapTypes"

export const locations: {
    [key: string]: Location
} = {
    "5": {
        id: "5",
        locationName: "Mimi Market",
        address: "12923 San Fernando Rd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "69",
        searchLink: "Mimi Market 12923 San Fernando Rd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "LOW",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.304894,
            long: -118.466998,
        },
    },
    "11": {
        id: "11",
        locationName: "Kwik Market And Deli",
        address: "15675 Roxford St, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "772",
        searchLink: "Kwik Market And Deli 15675 Roxford St, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Restaurant",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "primarily focused on selling sandwiches",
        position: {
            lat: 34.310028,
            long: -118.473645,
        },
    },
    "3": {
        id: "3",
        locationName: "Hacienda Market",
        address: "12441 San Fernando Rd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "1418",
        searchLink: "Hacienda Market 12441 San Fernando Rd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "LOW",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "they picked up the phone!",
        position: {
            lat: 34.296536,
            long: -118.456324,
        },
    },
    "15": {
        id: "15",
        locationName: "Carniceria La Esperanza",
        address: "13569 Glenoaks Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "1503",
        searchLink:
            "Carniceria La Esperanza 13569 Glenoaks Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.318378,
            long: -118.464463,
        },
    },
    "18": {
        id: "18",
        locationName: "El Rancho Plaza Market",
        address: "13566 Glenoaks Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "1565",
        searchLink:
            "El Rancho Plaza Market 13566 Glenoaks Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Restaurant",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "LOW",
        flagged: false,
        flagReason: "",
        comments:
            "meat store on store sign with pictures, but lacking more information",
        position: {
            lat: 34.318845,
            long: -118.463905,
        },
    },
    "19": {
        id: "19",
        locationName: "La Chuleta Fresca Prime & Grill #2",
        address: "13566 Glenoaks Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "1565",
        searchLink:
            "La Chuleta Fresca Prime & Grill #2 13566 Glenoaks Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.318848,
            long: -118.463907,
        },
    },
    "9": {
        id: "9",
        locationName: "Food 4 Less",
        address: "12689 Glenoaks Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "2442",
        searchLink: "Food 4 Less 12689 Glenoaks Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.299754,
            long: -118.441947,
        },
    },
    "31": {
        id: "31",
        locationName: "Olive View Medical Center Cfm",
        address: "14445 Olive View Dr, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "2759",
        searchLink:
            "Olive View Medical Center Cfm 14445 Olive View Dr, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Farmer's Market",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "Farmer's Market, would validate meat and dairy columns",
        position: {
            lat: 34.325759,
            long: -118.45104,
        },
    },
    "12": {
        id: "12",
        locationName: "Smart & Final #323",
        address: "2040 Glenoaks Blvd, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "2763",
        searchLink:
            "Smart & Final #323 2040 Glenoaks Blvd, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.298568,
            long: -118.438717,
        },
    },
    "13": {
        id: "13",
        locationName: "Vallarta Supermarket",
        address: "757 S Workman St, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "2862",
        searchLink:
            "Vallarta Supermarket 757 S Workman St, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.28268,
            long: -118.452543,
        },
    },
    // "14": {
    //     id: "14",
    //     locationName: "Rite Aid",
    //     address: "14727 Rinaldi St, San Fernando, CA 91340",
    //     hasEBT: true,
    //     hasMarketMatch: false,
    //     rewards: "null",
    //     coupons: "null",
    //     season_1_start: "",
    //     season_1_end: "",
    //     season_2_start: "",
    //     season_2_end: "",
    //     days: "",
    //     frequency: "",
    //     time_open: "",
    //     time_close: "",
    //     sylmarDistance: "2934",
    //     searchLink: "Rite Aid 14727 Rinaldi St, San Fernando, CA 91340",
    //     websiteURL: "null",
    //     storeType: "Pharmacy",
    //     freshFruit: "NONE",
    //     freshVegetables: "NONE",
    //     freshDairy: "NONE",
    //     unprocessedMeat: "NONE",
    //     flagged: false,
    //     flagReason: "",
    //     comments: "Would omit from the overall list",
    //     position: {
    //         lat: 34.281158,
    //         long: -118.454448,
    //     },
    // },
    "21": {
        id: "21",
        locationName: "Villalongin Market",
        address: "13947 Foothill Blvd #101, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "2943",
        searchLink:
            "Villalongin Market 13947 Foothill Blvd #101, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Bakery",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "Would omit from the overall list",
        position: {
            lat: 34.313497,
            long: -118.43732,
        },
    },
    "596": {
        id: "596",
        locationName: "Olive View-UCLA Medical Center Farmers' Market",
        address: "14445 Olive View Dr, Sylmar, 91342",
        hasEBT: false,
        hasMarketMatch: true,
        rewards: "null",
        coupons: "null",
        season_1_start: "Year Round",
        season_1_end: "null",
        season_2_start: "null",
        season_2_end: "null",
        days: "Friday",
        frequency: "null",
        time_open: "9:00:00",
        time_close: "14:00:00",
        sylmarDistance: "3069",
        searchLink:
            "Olive View-UCLA Medical Center Farmers' Market 14445 Olive View Dr, Sylmar, 91342",
        websiteURL: "null",
        storeType: "Farmer's Market",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "Duplicate of ID31, would check image for meat and dairy",
        position: {
            lat: 34.32621,
            long: -118.446163,
        },
    },
    "16": {
        id: "16",
        locationName: "El Super",
        address: "315 San Fernando Mission Blvd, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3136",
        searchLink:
            "El Super 315 San Fernando Mission Blvd, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.28434,
            long: -118.444695,
        },
    },
    "23": {
        id: "23",
        locationName: "Vons",
        address: "13730 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3191",
        searchLink: "Vons 13730 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.308293,
            long: -118.433196,
        },
    },
    "26": {
        id: "26",
        locationName: "Pioneer Market Inc.",
        address: "465 S Brand Blvd, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3621",
        searchLink:
            "Pioneer Market Inc. 465 S Brand Blvd, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "LOW",
        flagged: false,
        flagReason: "",
        comments: "Likely would not include, sells just meat",
        position: {
            lat: 34.279959,
            long: -118.442763,
        },
    },
    "33": {
        id: "33",
        locationName: "Orchard's Neighborhood Market",
        address: "13221 Gladstone Ave, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3627",
        searchLink:
            "Orchard's Neighborhood Market 13221 Gladstone Ave, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.311,
            long: -118.42889,
        },
    },
    "45": {
        id: "45",
        locationName: "Brothers Fresh Markeplace",
        address: "118581/2 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3705",
        searchLink:
            "Brothers Fresh Markeplace 118581/2 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.2863,
            long: -118.500907,
        },
    },
    "29": {
        id: "29",
        locationName: "Ziggy's Meat Market",
        address: "965 N Maclay Ave, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3902",
        searchLink:
            "Ziggy's Meat Market 965 N Maclay Ave, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.293574,
            long: -118.42764,
        },
    },
    "32": {
        id: "32",
        locationName: "Ed's Market",
        address: "972 N Maclay Ave, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "3954",
        searchLink: "Ed's Market 972 N Maclay Ave, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "Needs more information",
        position: {
            lat: 34.293354,
            long: -118.427126,
        },
    },
    "41": {
        id: "41",
        locationName: "Alta Dena Express",
        address: "16138 San Fernando Mission Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4022",
        searchLink:
            "Alta Dena Express 16138 San Fernando Mission Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Other (Not Recommended)",
        comments: "Mostly unhealthy food options",
        position: {
            lat: 34.271611,
            long: -118.484001,
        },
    },
    "42": {
        id: "42",
        locationName: "Sanamyan Meat & Grill",
        address: "16156 San Fernando Mission Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4040",
        searchLink:
            "Sanamyan Meat & Grill 16156 San Fernando Mission Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.271528,
            long: -118.484252,
        },
    },
    "38": {
        id: "38",
        locationName: "Mother's Nutritional Center #242",
        address: "1161 N Maclay Ave, San Fernando, CA 91340",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4110",
        searchLink:
            "Mother's Nutritional Center #242 1161 N Maclay Ave, San Fernando, CA 91340",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.295867,
            long: -118.424423,
        },
    },
    "56": {
        id: "56",
        locationName: "Island Pacific Supermarket #27",
        address: "11130 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4658",
        searchLink:
            "Island Pacific Supermarket #27 11130 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.27319,
            long: -118.500401,
        },
    },
    "58": {
        id: "58",
        locationName: "Granada International Market",
        address: "11116 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4720",
        searchLink:
            "Granada International Market 11116 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.272515,
            long: -118.500469,
        },
    },
    "57": {
        id: "57",
        locationName: "Vons",
        address: "16830 San Fernando Mission Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4764",
        searchLink:
            "Vons 16830 San Fernando Mission Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.270979,
            long: -118.498896,
        },
    },
    "59": {
        id: "59",
        locationName: "Trader Joe's",
        address: "11114 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4775",
        searchLink: "Trader Joe's 11114 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL: "https://locations.traderjoes.com/ca/granada-hills/44/",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.272659,
            long: -118.501605,
        },
    },
    "67": {
        id: "67",
        locationName: "Target Store",
        address: "11133 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "4886",
        searchLink: "Target Store 11133 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL:
            "https://www.target.com/c/same-day-delivery/-/N-bswkz?cpng=GMB_PlaceOrder_2329S&rwg_token=AJKvS9XYTFSF_SKP7h0tivzgzjJvl_Mf7_43iMKMoxiEebjqquSSWkrqpuzUynwpzimtYHuerOXe7p1IlYaNPyF8lCWOQIqx1A%3D%3D",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.272872,
            long: -118.503697,
        },
    },
    "50": {
        id: "50",
        locationName: "Target #3218",
        address: "10340 Sepulveda Blvd, Mission Hills, CA 91345",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5175",
        searchLink:
            "Target #3218 10340 Sepulveda Blvd, Mission Hills, CA 91345",
        websiteURL:
            "https://www.target.com/c/same-day-delivery/-/N-bswkz?cpng=GMB_PlaceOrder_2329S&rwg_token=AJKvS9XYTFSF_SKP7h0tivzgzjJvl_Mf7_43iMKMoxiEebjqquSSWkrqpuzUynwpzimtYHuerOXe7p1IlYaNPyF8lCWOQIqx1A%3D%3D",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.258664,
            long: -118.466531,
        },
    },
    "53": {
        id: "53",
        locationName: "Vons",
        address: "10321 Sepulveda Blvd, Mission Hills, CA 91345",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5214",
        searchLink: "Vons 10321 Sepulveda Blvd, Mission Hills, CA 91345",
        websiteURL:
            "https://www.vons.com/?cmpid=seo_allb_alld_ecom_gmplaor&rwg_token=AJKvS9XXlxNJsi8zG7mZHkca5Uz2pL7b9aN5VACVflIaDY6nvZzssLtuFqj-R_DrncP6VJMn-v0xnNxbN-schTysCiHEn3to8w%3D%3D",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.258306,
            long: -118.468252,
        },
    },
    "46": {
        id: "46",
        locationName: "Costco Wholesale #1071",
        address: "13550 Paxton St, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5283",
        searchLink: "Costco Wholesale #1071 13550 Paxton St, Pacoima, CA 91331",
        websiteURL:
            "https://www.costco.com/warehouse-locations/pacoima-ca-1071.html",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.27188,
            long: -118.426716,
        },
    },
    "47": {
        id: "47",
        locationName: "El Sauz Meat Market",
        address: "13236 Paxton St, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5329",
        searchLink: "El Sauz Meat Market 13236 Paxton St, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.277198,
            long: -118.420646,
        },
    },
    "74": {
        id: "74",
        locationName: "Smart & Final #460",
        address: "16210 Devonshire St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5637",
        searchLink:
            "Smart & Final #460 16210 Devonshire St, North Hills, CA 91343",
        websiteURL: "https://www.smartandfinal.com/store",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.256752,
            long: -118.485758,
        },
    },
    "52": {
        id: "52",
        locationName: "La Bodega Meat And Produce Inc",
        address: "10915 San Fernando Rd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5661",
        searchLink:
            "La Bodega Meat And Produce Inc 10915 San Fernando Rd, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.268402,
            long: -118.425131,
        },
    },
    "55": {
        id: "55",
        locationName: "Smart & Final #372",
        address: "10893 San Fernando Rd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5728",
        searchLink:
            "Smart & Final #372 10893 San Fernando Rd, Pacoima, CA 91331",
        websiteURL: "https://www.smartandfinal.com/store",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.267867,
            long: -118.424753,
        },
    },
    "61": {
        id: "61",
        locationName: "Numero Uno Market",
        address: "10455 Laurel Canyon Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "5955",
        searchLink:
            "Numero Uno Market 10455 Laurel Canyon Blvd, Pacoima, CA 91331",
        websiteURL: "https://superiorgrocers.com/locations/",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.259407,
            long: -118.434108,
        },
    },
    "66": {
        id: "66",
        locationName: "Mother's Nutritional Center #612",
        address: "13643 Van Nuys Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6033",
        searchLink:
            "Mother's Nutritional Center #612 13643 Van Nuys Blvd, Pacoima, CA 91331",
        websiteURL: "https://mothersnc.com/",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.260637,
            long: -118.430252,
        },
    },
    "64": {
        id: "64",
        locationName: "Food 4 Less",
        address: "12765 Van Nuys Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6068",
        searchLink: "Food 4 Less 12765 Van Nuys Blvd, Pacoima, CA 91331",
        websiteURL:
            "https://www.food4less.com/stores/grocery/ca/pacoima/n-pacoima/704/00377",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.275409,
            long: -118.412385,
        },
    },
    "83": {
        id: "83",
        locationName: "Victory Produce",
        address: "10365 Balboa Blvd, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6072",
        searchLink:
            "Victory Produce 10365 Balboa Blvd, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.259025,
            long: -118.502946,
        },
    },
    "65": {
        id: "65",
        locationName: "El Toro Grande Market",
        address: "13158 Van Nuys Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6084",
        searchLink:
            "El Toro Grande Market 13158 Van Nuys Blvd, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.267891,
            long: -118.419285,
        },
    },
    "600": {
        id: "600",
        locationName: "El Nido Farmers' Market",
        address: "11243 Glenoaks Blvd.\u00a0, Pacoima, 91331",
        hasEBT: false,
        hasMarketMatch: true,
        rewards: "null",
        coupons: "null",
        season_1_start: "Year Round",
        season_1_end: "null",
        season_2_start: "null",
        season_2_end: "null",
        days: "Saturday",
        frequency: "null",
        time_open: "9:00:00",
        time_close: "14:00:00",
        sylmarDistance: "6124",
        searchLink:
            "El Nido Farmers' Market 11243 Glenoaks Blvd.\u00a0, Pacoima, 91331",
        websiteURL: "https://www.elnidofamilycenters.org/farmers-market",
        storeType: "Farmer's Market",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.274191,
            long: -118.41264,
        },
    },
    "72": {
        id: "72",
        locationName: "Rite Aid",
        address: "12739 Van Nuys Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6188",
        searchLink: "Rite Aid 12739 Van Nuys Blvd, Pacoima, CA 91331",
        websiteURL:
            "https://www.riteaid.com/locations/ca/pacoima/12739-van-nuys-boulevard.html",
        storeType: "Pharmacy",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.275298,
            long: -118.410925,
        },
    },
    "85": {
        id: "85",
        locationName: "Ralphs",
        address: "16940 Devonshire St, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6224",
        searchLink: "Ralphs 16940 Devonshire St, Granada Hills, CA 91344",
        websiteURL:
            "https://www.ralphs.com/stores/grocery/ca/granada-hills/north-hills-sc/703/00704",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.256727,
            long: -118.501532,
        },
    },
    "75": {
        id: "75",
        locationName: "Best Live Poultry & Fish, Llc",
        address: "12253 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6486",
        searchLink:
            "Best Live Poultry & Fish, Llc 12253 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.282303,
            long: -118.402806,
        },
    },
    "76": {
        id: "76",
        locationName: "Araz Market",
        address: "12251 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6495",
        searchLink: "Araz Market 12251 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Restaurant",
        freshFruit: "",
        freshVegetables: "",
        freshDairy: "",
        unprocessedMeat: "",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.282241,
            long: -118.402737,
        },
    },
    "93": {
        id: "93",
        locationName: "Hovik's Famous Meat & Deli",
        address: "17660 Chatsworth St, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6575",
        searchLink:
            "Hovik's Famous Meat & Deli 17660 Chatsworth St, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.264508,
            long: -118.51957,
        },
    },
    "95": {
        id: "95",
        locationName: "Rite Aid #5553",
        address: "10823 Zelzah Ave, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6697",
        searchLink: "Rite Aid #5553 10823 Zelzah Ave, Granada Hills, CA 91344",
        websiteURL:
            "https://www.riteaid.com/locations/ca/granada-hills/10823-zelzah-avenue.html",
        storeType: "Pharmacy",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.266877,
            long: -118.52388,
        },
    },
    "81": {
        id: "81",
        locationName: "El Super",
        address: "9710 Woodman Ave, Arleta, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6705",
        searchLink: "El Super 9710 Woodman Ave, Arleta, CA 91331",
        websiteURL: "https://elsupermarkets.com/store/arleta/",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.247641,
            long: -118.445973,
        },
    },
    "96": {
        id: "96",
        locationName: "Sprouts Farmers Market #223",
        address: "10821 Zelzah Ave, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6732",
        searchLink:
            "Sprouts Farmers Market #223 10821 Zelzah Ave, Granada Hills, CA 91344",
        websiteURL:
            "https://www.sprouts.com/store/ca/granada-hills/n-zelzah-ave/",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.266717,
            long: -118.524206,
        },
    },
    "100": {
        id: "100",
        locationName: "Araz International Grocery Maeket",
        address: "10668 Zelzah Ave, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6822",
        searchLink:
            "Araz International Grocery Maeket 10668 Zelzah Ave, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.264308,
            long: -118.523002,
        },
    },
    "101": {
        id: "101",
        locationName: "Supreme Butchery",
        address: "10654 Zelzah Ave, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6853",
        searchLink:
            "Supreme Butchery 10654 Zelzah Ave, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "LOW",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.263886,
            long: -118.522988,
        },
    },
    "104": {
        id: "104",
        locationName: "Ralphs Grocery Co.",
        address: "18010 Chatsworth St, Granada Hills, CA 91344",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "6981",
        searchLink:
            "Ralphs Grocery Co. 18010 Chatsworth St, Granada Hills, CA 91344",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.263236,
            long: -118.524165,
        },
    },
    "82": {
        id: "82",
        locationName: "El Milagro Panaderia, Inc.",
        address: "12040 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7058",
        searchLink:
            "El Milagro Panaderia, Inc. 12040 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Bakery",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.277003,
            long: -118.398921,
        },
    },
    "86": {
        id: "86",
        locationName: "Lakeview Farm Market, Inc.",
        address: "11924 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7318",
        searchLink:
            "Lakeview Farm Market, Inc. 11924 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.275214,
            long: -118.396839,
        },
    },
    "90": {
        id: "90",
        locationName: "Carniceria La Consentida Meat Market",
        address: "11840 Foothill Blvd, Sylmar, CA 91342",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7546",
        searchLink:
            "Carniceria La Consentida Meat Market 11840 Foothill Blvd, Sylmar, CA 91342",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.273597,
            long: -118.39507,
        },
    },
    "98": {
        id: "98",
        locationName: "Vallarta Supermarkets #8",
        address: "9136 Sepulveda Blvd, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7632",
        searchLink:
            "Vallarta Supermarkets #8 9136 Sepulveda Blvd, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "Thursday 3\u20137:30\u202fPM",
        position: {
            lat: 34.236583,
            long: -118.466412,
        },
    },
    "91": {
        id: "91",
        locationName: "Vallarta Supermarkets #18",
        address: "10175 San Fernando Rd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7660",
        searchLink:
            "Vallarta Supermarkets #18 10175 San Fernando Rd, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.254928,
            long: -118.410747,
        },
    },
    "92": {
        id: "92",
        locationName: "Superior Grocers",
        address: "9801 Laurel Canyon Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7729",
        searchLink:
            "Superior Grocers 9801 Laurel Canyon Blvd, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.247021,
            long: -118.421717,
        },
    },
    "115": {
        id: "115",
        locationName: "7 Kings Mini Market",
        address: "17646 Lassen St, Northridge, CA 91325",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7767",
        searchLink: "7 Kings Mini Market 17646 Lassen St, Northridge, CA 91325",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.250033,
            long: -118.519487,
        },
    },
    "103": {
        id: "103",
        locationName: "Short Stop #23",
        address: "15400 Nordhoff St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7780",
        searchLink: "Short Stop #23 15400 Nordhoff St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.23525,
            long: -118.468146,
        },
    },
    "106": {
        id: "106",
        locationName: "Rocket #0167",
        address: "15712 Nordhoff St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7805",
        searchLink: "Rocket #0167 15712 Nordhoff St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.235253,
            long: -118.474535,
        },
    },
    "94": {
        id: "94",
        locationName: "California Deli Mini",
        address: "13205 Osborne St, Arleta, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7811",
        searchLink: "California Deli Mini 13205 Osborne St, Arleta, CA 91331",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.24657,
            long: -118.42092,
        },
    },
    "108": {
        id: "108",
        locationName: "Valley Seafood & Poultry Market",
        address: "9023 Sepulveda Blvd, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7897",
        searchLink:
            "Valley Seafood & Poultry Market 9023 Sepulveda Blvd, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "LOW",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.234202,
            long: -118.468102,
        },
    },
    "109": {
        id: "109",
        locationName: "Toyin's African Market",
        address: "9005 Sepulveda Blvd, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7916",
        searchLink:
            "Toyin's African Market 9005 Sepulveda Blvd, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Other (Not Recommended)",
        comments: "",
        position: {
            lat: 34.234026,
            long: -118.467953,
        },
    },
    "97": {
        id: "97",
        locationName: "La Potosina Meat & Market",
        address: "13439 Osborne St, Arleta, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7946",
        searchLink:
            "La Potosina Meat & Market 13439 Osborne St, Arleta, CA 91331",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.242558,
            long: -118.426143,
        },
    },
    "112": {
        id: "112",
        locationName: "Seafood City Supermarket",
        address: "16130 Nordhoff St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "7967",
        searchLink:
            "Seafood City Supermarket 16130 Nordhoff St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.234832,
            long: -118.483877,
        },
    },
    "99": {
        id: "99",
        locationName: "Target Store",
        address: "9725 Laurel Canyon Blvd, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8021",
        searchLink: "Target Store 9725 Laurel Canyon Blvd, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.245145,
            long: -118.419397,
        },
    },
    "107": {
        id: "107",
        locationName: "Walmart Neighborhood Market",
        address: "14530 Nordhoff St, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8064",
        searchLink:
            "Walmart Neighborhood Market 14530 Nordhoff St, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.234427,
            long: -118.44866,
        },
    },
    "111": {
        id: "111",
        locationName: "Panaderia Y Mercado La Fiesta",
        address: "8925 Sepulveda Blvd, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8104",
        searchLink:
            "Panaderia Y Mercado La Fiesta 8925 Sepulveda Blvd, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Bakery",
        freshFruit: "LOW",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.232344,
            long: -118.468193,
        },
    },
    "105": {
        id: "105",
        locationName: "Food 4 Less",
        address: "9635 Laurel Canyon Blvd, Arleta, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8233",
        searchLink: "Food 4 Less 9635 Laurel Canyon Blvd, Arleta, CA 91331",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.243857,
            long: -118.417588,
        },
    },
    "133": {
        id: "133",
        locationName: "Smart & Final #420",
        address: "18555 Devonshire St, Northridge, CA 91324",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8286",
        searchLink:
            "Smart & Final #420 18555 Devonshire St, Northridge, CA 91324",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.258399,
            long: -118.537805,
        },
    },
    "136": {
        id: "136",
        locationName: "Galleria Market/Northridge Lp",
        address: "10201 Reseda Blvd, Northridge, CA 91324",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8410",
        searchLink:
            "Galleria Market/Northridge Lp 10201 Reseda Blvd, Northridge, CA 91324",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.256108,
            long: -118.537244,
        },
    },
    "113": {
        id: "113",
        locationName: "Vallarta Supermarket",
        address: "9011 Woodman Ave, Arleta, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8413",
        searchLink: "Vallarta Supermarket 9011 Woodman Ave, Arleta, CA 91331",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.233209,
            long: -118.439643,
        },
    },
    "125": {
        id: "125",
        locationName: "Albertsons",
        address: "9022 Balboa Blvd, Northridge, CA 91325",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8460",
        searchLink: "Albertsons 9022 Balboa Blvd, Northridge, CA 91325",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.234443,
            long: -118.50145,
        },
    },
    "116": {
        id: "116",
        locationName: "99 Cents Only Store #227",
        address: "8723 Sepulveda Blvd, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8468",
        searchLink:
            "99 Cents Only Store #227 8723 Sepulveda Blvd, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Dollar Store",
        comments: "",
        position: {
            lat: 34.229077,
            long: -118.468969,
        },
    },
    "117": {
        id: "117",
        locationName: "Kumar & Narang Genl #None",
        address: "15331 Parthenia St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8533",
        searchLink:
            "Kumar & Narang Genl #None 15331 Parthenia St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.228488,
            long: -118.46665,
        },
    },
    "128": {
        id: "128",
        locationName: "Target Store",
        address: "8999 Balboa Blvd, Northridge, CA 91325",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8533",
        searchLink: "Target Store 8999 Balboa Blvd, Northridge, CA 91325",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.234435,
            long: -118.503519,
        },
    },
    "118": {
        id: "118",
        locationName: "Mercado El Rey 5",
        address: "15256 Parthenia St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8580",
        searchLink:
            "Mercado El Rey 5 15256 Parthenia St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "NONE",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.228089,
            long: -118.46529,
        },
    },
    "122": {
        id: "122",
        locationName: "Smiley's Market",
        address: "14712 Parthenia St, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8712",
        searchLink:
            "Smiley's Market 14712 Parthenia St, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "",
        position: {
            lat: 34.227682,
            long: -118.454152,
        },
    },
    "114": {
        id: "114",
        locationName: "One Stop Mini Mart",
        address: "12906 Branford St, Pacoima, CA 91331",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8760",
        searchLink: "One Stop Mini Mart 12906 Branford St, Pacoima, CA 91331",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: true,
        flagReason: "Liquor Store",
        comments: "RATS",
        position: {
            lat: 34.240529,
            long: -118.413332,
        },
    },
    "148": {
        id: "148",
        locationName: "Amazon Northridge",
        address: "19340 Rinaldi St, Northridge, CA 91326",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8767",
        searchLink: "Amazon Northridge 19340 Rinaldi St, Northridge, CA 91326",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.273457,
            long: -118.554959,
        },
    },
    "130": {
        id: "130",
        locationName: "Food 4 Less",
        address: "16208 Parthenia St, North Hills, CA 91343",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8790",
        searchLink: "Food 4 Less 16208 Parthenia St, North Hills, CA 91343",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.227611,
            long: -118.485849,
        },
    },
    "123": {
        id: "123",
        locationName: "Tapalchulteca",
        address: "8640 Van Nuys Blvd, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8836",
        searchLink: "Tapalchulteca 8640 Van Nuys Blvd, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Bakery",
        freshFruit: "LOW",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.227179,
            long: -118.449627,
        },
    },
    "124": {
        id: "124",
        locationName: "El Super",
        address: "14620 Parthenia St, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8921",
        searchLink: "El Super 14620 Parthenia St, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.226223,
            long: -118.450835,
        },
    },
    "126": {
        id: "126",
        locationName: "Food 4 Less",
        address: "8530 Tobias Ave, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "8981",
        searchLink: "Food 4 Less 8530 Tobias Ave, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.225655,
            long: -118.450954,
        },
    },
    "127": {
        id: "127",
        locationName: "Mother's Nutritional Center #450",
        address: "8530 Van Nuys Blvd, Panorama City, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "9021",
        searchLink:
            "Mother's Nutritional Center #450 8530 Van Nuys Blvd, Panorama City, CA 91402",
        websiteURL: "null",
        storeType: "Convenience Store",
        freshFruit: "LOW",
        freshVegetables: "LOW",
        freshDairy: "LOW",
        unprocessedMeat: "NONE",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.225638,
            long: -118.448699,
        },
    },
    "145": {
        id: "145",
        locationName: "Cal State Northridge Cfm",
        address: "18111 Nordhoff St, Northridge, CA 91325",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "9041",
        searchLink:
            "Cal State Northridge Cfm 18111 Nordhoff St, Northridge, CA 91325",
        websiteURL: "null",
        storeType: "Farmer's Market",
        freshFruit: "",
        freshVegetables: "",
        freshDairy: "",
        unprocessedMeat: "",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.239916,
            long: -118.526252,
        },
    },
    "164": {
        id: "164",
        locationName: "India Sweets & Grocery",
        address: "18110 Parthenia St, Northridge, CA 91325",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "10245",
        searchLink:
            "India Sweets & Grocery 18110 Parthenia St, Northridge, CA 91325",
        websiteURL: "null",
        storeType: "Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "LOW",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.227934,
            long: -118.528315,
        },
    },
    "154": {
        id: "154",
        locationName: "Van Nuys Live & Fresh Poultry",
        address: "14547 Arminta St, Van Nuys, CA 91402",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "10279",
        searchLink:
            "Van Nuys Live & Fresh Poultry 14547 Arminta St, Van Nuys, CA 91402",
        websiteURL: "null",
        storeType: "Meat",
        freshFruit: "NONE",
        freshVegetables: "NONE",
        freshDairy: "LOW",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.213903,
            long: -118.45049,
        },
    },
    "155": {
        id: "155",
        locationName: "Target Store",
        address: "14920 Raymer St, Van Nuys, CA 91405",
        hasEBT: true,
        hasMarketMatch: false,
        rewards: "null",
        coupons: "null",
        season_1_start: "",
        season_1_end: "",
        season_2_start: "",
        season_2_end: "",
        days: "",
        frequency: "",
        time_open: "",
        time_close: "",
        sylmarDistance: "10310",
        searchLink: "Target Store 14920 Raymer St, Van Nuys, CA 91405",
        websiteURL: "null",
        storeType: "Big Grocery",
        freshFruit: "HIGH",
        freshVegetables: "HIGH",
        freshDairy: "HIGH",
        unprocessedMeat: "HIGH",
        flagged: false,
        flagReason: "",
        comments: "",
        position: {
            lat: 34.212778,
            long: -118.459339,
        },
    },
}
